top-think/framework

library/think/cache/driver/File.php
linux可能出现 . 或者 .. 特殊目录，在进行is_dir时，会报错
=> 修复File缓存方式下，clear报错误

library/think/cache/driver/Redisd.php, tests/thinkphp/library/think/cache/driver/redisdTest.php
Redisd驱动与Redis驱动的区别:
> Redis3.0以上自带了redisCluster来实现集群功能，需要使用最新的Redis扩展才能支持
Redisd驱动与Redis驱动的使用场景:
>Redis驱动适用于单机部署Redis的业务，效率最高，支持Proxy模式，不支持redisCluster模式
>Redis驱动适用于多机部署Redis的业务，支持Proxy模式，支持redisCluster模式(正在生产测试)
Redisd驱动在支持redis的同时，添加了主从及读写分离的功能，在RedisCluster功能完成严格生产测试以后，也会添加到Redisd驱动中。
配置参数:
```php
'cache' => [
'type'       => 'Redisd'
'host'       => 'A:6379,B:6379', //redis服务器ip，多台用逗号隔开；读写分离开启时，默认写A，当A主挂时，再尝试写B
'slave'      => 'B:6379,C:6379', //redis服务器ip，多台用逗号隔开；读写分离开启时，所有IP随机读，其中一台挂时，尝试读其它节点，可以配置权重
'port'       => 6379,    //默认的端口号
'password'   => '',      //AUTH认证密码，当redis服务直接暴露在外网时推荐
'timeout'    => 10,      //连接超时时间
'expire'     => false,   //默认过期时间，默认0为永不过期
'prefix'     => '',      //缓存前缀，不宜过长
'persistent' => false,   //是否长连接 false=短连接，推荐长连接
],
```  
单例获取:
```php
$redis = …
```
=> 添加Redisd驱动及单元测试

library/think/Url.php
不知道我这改合不合适，流年可以试一下 在开启 域名路由的时候url 的输出结果，我这边测试有bug就改了
// 域名部署
'url_domain_deploy'      => true,  // 域名部署
// 域名路由
'domain' => [
'admin' => 'admin',
'api' => 'api',
'store' => 'store',
'supplier' => 'supplier',
'.store' => 'store',
'.supplier' => 'supplier',
],
然后通过 store.test.com www.test.com 对应的 index 控制器 输出 url('index'); 有问题， 可以测试一下看看然后再决定是否合并
=> 修改在使用域名路由时，url方法结果不正确的bug(优化parseDomain)

library/think/Model.php
经常遇到的坑是：
比如新增 a b c d 4个字段内容，进行新增操作调用save方法。由于save对$data是进行遍历调用修改器，导致当前对象的$this->data并不完整。例如b字段是和d字段有一定关联关系的，因为是foreach的方式，导致执行到d的修改器时，压根在$data参数获取不到d的值！，虽然可以在修改器里，直接获取外部提交的变量，但这种方式，不完美！如果我不是外部获取的数据呢？那岂不是没辙了！
=> 优化set修改器，$data不完整

library/think/template/driver/File.php
,先判断缓存文件是否存在, 如果文件不存在而直接调用filemtime会报错
=> 修复 检测模板缓存是否有效 方法bug

library/think/db/builder/Sqlsrv.php
带order参数查询时，取值错误，取的$order[0]内容是第一个字母r。
生成update语句时，ORDER应该替换成空(MSSQL的update语句中不支持order)
=> 修正mssql查询和更新时生成语句的错误

library/think/db/builder/Sqlsrv.php
删除数据时不应该有ORDER，否则在MSSQL中会报错。
定义$deleteSql方式解决。
=> 修正mssql 删除数据时错误

library/think/db/builder/Sqlsrv.php
mssql中为实现排序增加了row_number列，导致在selectInsert方法中字段数不一致。
修正方法：定义selectInsertSql属性，重写selectInsert方法。
=> 修正selectInsert方法字段数不一致错误

library/think/db/Query.php
当$dataSet不包含索引0的时候，会抛出异常，如：$dataSet = [1=>[……],'str'=>[……],……];
=> 修正$dataSet不存在索引0导致异常的情况

library/think/session/driver/Memcached.php
Memcached在关闭时与Memcache调用的方法不同，应该使用quit方法进行关闭所有连接的操作。此前使用错了关闭方法，导致在操作session的时候服务器返回500错误。
详见：http://php.net/manual/en/memcached.quit.php
=> 修正了Memcached关闭时调用的方法。

library/think/Model.php
防止array和object类型数据为null时，导致调用发生异常。
=> 读取时增加空检测，防止数据为空导致调用异常

library/think/Model.php
1.修正$name为array类型时的BUG
2.范围方法调用支持多参数传入
=> 修正scope方法$name参数传入array引起$names变量不存在的异常

library/think/db/builder/Sqlsrv.php
query->table('a')->join('b','b.id=a.map')->where('b.id=1')->update($data);
以上应用时update生成的sql语句语法错误。
更正方法：join前增加from 源表名
=> 修正MSSQL的UPDATE语句语法错误

library/think/Template.php, library/think/template/TagLib.php
报错的PHP环境 PHP5.6 pcre6.6
报错信息：
preg_match(): Compilation failed: unrecognized character after (?&lt; at offset 46
=> 修复了在php5.4以上版本中pcre库版本略低出现的preg_match或preg_match_all函数报无法识别字符错误，并且可以向上兼容

library/think/db/Query.php
由于在缓存中存放的递减值为负值，所以这里在拿出这个缓存值(缓存值本身为负值)后运算符应该为+，否则的话运算结果是错误的。
=> 修正了延迟递减时实际为递增的错误。

library/think/cache/driver/Memcached.php
1.之前由于递增减的键值对的键是没有加前缀的，而移除这个记录增减的键值对时移除的是加前缀的，所以会导致移除时失败，最终造成递增减数值错误。
2.由于Memcached的decrement方法递减到0以后就不会再减小了，所以这里就会造成递减的数值不对。只好自己写一个递减的方法了。
该方法说明详见http://php.net/manual/zh/memcached.decrement.php
=> 修正了延迟递增减后不能清空的计数的问题、修正了延迟递减，数值小于零时不能递减的问题

library/think/Request.php
若HTTP请求中HTTP_ACCEPT参数缺失会导致页面错误，因此首先需要判断一下该参数是否存在
=> 修正“isMobile”方法，防止在特殊情况下崩溃

library/think/log/driver/File.php, library/think/log/driver/Socket.php
修复$runtime为0时,计算吞吐率出现'Division by zero'异常，错误信息：
``Fatal error: Uncaught exception 'think\exception\ErrorException' with message 'Division by zero'
=> 计算吞吐率出现的'Division by zero'异常

library/think/cache/driver/Redis.php, library/think/session/driver/Redis.php
* 增加cache/session redis驱动的库选择逻辑;
* hint: 需要在缓存配置(cache节点)中增加'select';
* eg: ['cache' => ['select'=>0, ...]];
=> 增加cache/session redis驱动的库选择 fixed #253

library/think/Request.php
=> 解决 php7 数组指针问题

library/think/Model.php
解决Model类db()方法在$this->field=true时重复被调用的而引发的问题
=> 解决Model类db()方法在$this->field=true时重复被调用的而引发的问题

library/think/Validate.php
修改条件为strpos($message, '{%') === 0
=> 修复验证器规则无法获取多语言的问题

library/think/Request.php
在phpstorm2016.2.1中，使用下列语句会提示警告： 
>Method __toString is not implemented for '\think\Request' less... (Ctrl+F1) 
>This inspection detects attempts to convert objects without __toString() method implementation to string, since PHP 5.2.0, it would cause E_RECOVERABLE_ERROR. "Check __toString exists for each expression type": if the option is on, the inspection will check all possible types of the expression and report if at least one ot them doesn't contain __toString() method implementation. 
```
$request = Request::instance();
echo "当前模块名称是" . $request->module();// 这句会被IDE提示警告
echo "当前控制器名称是" . $request->controller();// 这句会被IDE提示警告
echo "当前操作名称是" . $request->action();// 这句就不会
```
后来发现是注释引起的问题，注释中有`@return string|$this`。而action()方法却写成`@return string`。个人认为应该统一写成`@return string|Request` …
=> 为Request类的几个方法完善注释

library/think/Validate.php
在做验证通用操作功能封装的时候，可以根据需要，是否启用场景验证
=> 增加 判断是否存在某个场景的验证配置

library/think/Request.php
目前RESTful API用json方式提交的很多
目前PUT/PATCH/DELETE方法均可以支持json，但POST方法不能，这不对等
其实更好的方法是判断header里content-type是否为application/json，但因为目前header属性采用的是懒加载，所以暂时沿用目前的字符串判断
=> 让Request支持json方式的POST

library/traits/controller/Jump.php
error方法在ajax请求，默认返回url改为空，更合适，而且TP历史版本，返回url也是空
=> error方法在ajax请求，默认返回url改为空

library/think/Console.php
这样在命令行下，调用别的命令行，可以直接一行一行地输出日志，而不用等到buffer完，才输出
=> 可以允许自定义Output的driver，以适应命令行模式下调用其它命令行指令

convention.php
HTTP下开启此配置后，浏览器不会发送前一个请求中服务器返回的PHPSESSID
=> 默认关闭session的安全传输，此选项仅能在HTTPS下设置开启

library/think/Config.php
分割后的$name只用到0和1键，因此explode加上limit参数
修改后还可以支持Config::set('abc.def.g')这种用法
=> 配置参数名只分割为两部分

library/think/console/command/Clear.php
之前的问题是log目录下日期目录下的日志文件无法清除。现在不论多少级都可以清除了
=> 修复clear指令无法删除多级目录下文件的问题

library/think/Session.php
Session在执行第一次set或者get等操作后才会执行一次Session初始化。
而在此之前调用Session::prefix('xxx');方法设置当前控制器的Session作用域会被之后的第一次set或者get等操作调用self::init();覆盖Session::prefix('xxx');设置。
我这里的改变使得可以在第一次session操作之前通过Session::prefix('xxx');有效设置作用域
=> 修复Session::prefix('xxx');设置当前作用域BUG

library/think/console/command/optimize/Schema.php
多个数据库配置的情况下，仅用一个`--db`数据库名参数是无法满足的，所以这里加一个`--config`参数，也就是传入`Db::connect($config)` 方法的值。
=> 命令行工具schema增加config参数，支持传入数据库连接配置

library/think/console/command/optimize/Autoload.php
主要是因为 `realpath(EXTEND_PATH)` 函数得出结果为`false`后，后面没去作有效性判断。
=> 修复optimize:autoload命令在EXTEND_PATH目录不存在的情况下，类库映射生成错误问题

library/think/db/builder/Sqlsrv.php
Db::table('a')->join('b','a.map=b.id')
->where('b.id=1')->delete();
生成的语句是
delete from a inner join b on a.map=b.id where b.id=1 //这在mssql中存在语法错误！
正确的语句应该是delete from a  from a inner join b on a.map=b.id where b.id=1 
希望采纳！
=> 修正join其他表时生成的delete语句错误。

library/think/App.php
之前的代码逻辑中，如果配置扩展目录（ `CONF_PATH . $module . 'extra'` ）中有一个文件名中包含 `CONF_EXT` 字符串，但不是以 `CONF_EXT` 结尾，也会被自动加载。
修改为判断只有文件名以 `CONF_EXT` 结尾的情况，才会被自动加载。
e.g.
比如配置文件 `app.php`, 使用 vi 打开时会生成 `.app.php.swp` 临时文件。 APP::init() 内的逻辑会自动调 CONFIG::load, 但是 CONFIG::parse() 中发现没有 `\think\config\driver\swp` 类而报错。
=> 修复配置extra目录临时文件名中含CONF_EXT(如 vi 的 .swp 文件)被错误加载导致报错的问题

library/think/Log.php
我在进行多进程异步通信操作时，需要回收子进程，但是又不要影响日志输出，试了官方给出各个行为监听，都会中断log输出。我希望在这里加一个log存储完成的行为监听，这样就可以在log存储完成后，进行子进程回收工作。
=> library/think/Log.php 161行添加log存储完成行为监听

library/think/db/Builder.php
Db::table('think_user')->alias(['think_user'=>'user','think_dept'=>'dept'])->join('think_dept','dept.user_id= user.id')->select();
生成的SQL为 
SELECT * FROM think_user user INNER JOIN think_dept think_dept ON dept.user_id= user.id
修改后生成的SQL为 
SELECT * FROM think_user user INNER JOIN think_dept dept ON dept.user_id= user.id
=> 修复 传入数组批量设置数据表以及别名 bug

library/think/model/Collection.php
调用collection()->append(['关联'=>['属性']])，如果遇到某个模型对象的关联查询到null，则append会导致null object错误
=> Collection::append() 判断数据是否存在(null)

library/think/Controller.php, library/think/File.php, library/think/Lang.php, library/think/Loader.php, library/think/Model.php, library/think/Request.php, library/think/Route.php, library/think/Template.php, library/think/View.php, library/think/console/output/Descriptor.php, library/think/db/Builder.php, library/think/db/Connection.php, library/think/db/Query.php, library/think/db/builder/Sqlite.php, library/think/model/relation/BelongsTo.php
代码中部分函数存在**文档注释与实际不相符**的情况，进而进行了相关修复以及调整
１、修复形参类型/返回值与文档注释丢失/不匹配的情况
２、修复部分错别字，例如$lmit($limit),$locl($lock)
３、部分函数直接调用可能会引起错误,且由于未申明而直接调用，会引起部分IDE会直接报出警告。所以在调用前新增了判断。
=> 修改代码中若干处错别字以及注释错误

library/think/Lang.php
多语言自动切换时，优先使用COOKIE中的语言设置，方便保持用户自己选择的语言。
=> 优先使用Cookie中的语言设置

library/think/db/Builder.php, library/think/db/Query.php
原因是构造函数里设置了默认的表前缀，而自定义model的connect时，不会重新设置自定义的表前缀，导致自定义表前缀无效。
修复insert生成的sql语句错误。
重用`$fields`只用没有清空原有数据，导致生成的sql语句异常。
=> 修复model两个bug

tests/thinkphp/library/think/config/ConfigInitTrait.php, tests/thinkphp/library/think/config/driver/iniTest.php, tests/thinkphp/library/think/config/driver/jsonTest.php, tests/thinkphp/library/think/config/driver/xmlTest.php, tests/thinkphp/library/think/configTest.php, tests/thinkphp/library/think/controllerTest.php, tests/thinkphp/library/think/requestTest.php
目前部分测试用例在执行Config部分操作后会存在影响其他测试用例的情况。
譬如部分测试用例在执行中会调用Config::reset操作清空配置，最后会影响其他的测试用例。
例如在requestTest::isAjax中，会调用Config::get('var_ajax')，预期上理应返回convention中预设的值，然而Config在执行reset后清空了所有的值，导致后续的测试用例执行结果会与预期不符。
=> 调整Config相关单元测试用例

library/traits/controller/Jump.php, tests/thinkphp/library/think/urlTest.php, tests/thinkphp/library/traits/controller/.gitignore, tests/thinkphp/library/traits/controller/jumpTest.php
- 在Jump.php中，使用Request::instance()->server代替$_SERVER
- 新增JumpTrait的测试用例
=> 新增Jump相关测试用例

library/think/console/command/optimize/Route.php
如果RUNTIME_PATH目录不存在，单独执行这个命令会报错的
=> 执行路由缓存命令前检测RUNTIME_PATH是否存在

library/think/Route.php
list($name, $rule) = $rule; 中$rule变量名相同 在php5.6下$name值异常
=> 路由标识设置异常修复

library/think/Session.php, library/think/response/Jump.php, library/think/session/driver/Redis.php, library/traits/controller/Jump.php
后台使用Redis Session。在登录业务中，用ajax方式同时刷新了验证码和token后，登录时出现token令牌不存在的问题。
故丢Redis驱动和Session类进行了加锁处理，可通过配置文件开启加锁功能。
对Redis Session的具体测试，可参考：https://www.zybuluo.com/conna45/note/914918
代码调整:
think\session\driver\Redis类新增了两个方法，分别是lock()和unlock()
think\Session类新增三个属性$lockDriver、$sessKey、$lockTimeout和三个方法initDriver()、lock()、unlock()
启用lock：在配置文件里，设置'use_lock'       => true,  如果Session驱动没有实现lock和unlock函数，则不会加锁
=> Redis Session驱动和Jump跳转html渲染的修改

library/think/model/relation/BelongsTo.php, library/think/model/relation/BelongsToMany.php, library/think/model/relation/HasMany.php, library/think/model/relation/HasOne.php, library/think/model/relation/OneToOne.php
当关联表中定义了`$table = "exampleTable";`时，此时在关联查询时会自动加上系统数据库表前缀导致
报找不到`tp_example_table`表的错误，实则应该是直接使用`exampleTable`表
=> 修复在关联模型使用了自定义表名时的BUG

library/think/Validate.php
修复数组包含数字键名，后面的值将不会覆盖原来的值，而是附加到后面，且键名会以连续方式重新索引，导致规则中键名丢失的情况。
Fixed a problem that the arrays contain numeric keys, the later value will not overwrite the original value, but will be appended, and values in the input array with numeric keys will be renumbered with incrementing keys starting from zero in the result array, caused the keys to be lost in the rules.
=> 修复数字键名丢失问题

library/think/Loader.php
一些提供可执行文件的composer依赖，譬如phpunit，这些在运行时会先载入composer的autoload文件，这时，如果我在phpunit的bootstrap文件里面初始化了TP，那么TP内部的Loader依然会require一遍composer下的`files`，有可能导致函数的重复定义。
=> [5.0] 修复可能出现的重复require

library/think/Build.php
这里的 `$layer` 在后面递归时会传入多级控制器的命名空间，所以这里应该是固定的 `\`
=> 修复多级控制器的注解路由问题

library/think/Model.php
使 saveAll 批量添加带主键的数据时支持 replace()连贯操作，例如：model('goods')->replace()->saveAll($result, false);
=> 使 saveAll 批量添加带主键的数据时支持 replace()连贯操作

library/think/log/driver/Socket.php
- 默认`debug`级别信息在浏览器 console 输出时自动展开
- 通过配置`expand_level `选项自定义默认展开类别。方便调试。
=> 改进Socketlog扩展

library/think/model/relation/HasMany.php, library/think/model/relation/HasOne.php
举个栗子
ModelA extends Model {
protected $pk ="id";
public function b() {
return $this->hasMany("ModelB", "extra_aid", "extra_id");
}
}
ModelB extends Model {
protected $pk = "id";
}
$modelA = new ModelA;
$sql = $modelA->withCount("b")->fetchSql(true)->select();
这时候并不会按照理想的给出 b.extra_aid = a.extra_id
而是给出了b.extra_aid = a.id
所以我觉着这儿有问题。。
=> 定义模型时hasMany($model, $foreignKey, $localKey)有三个参数，这里getPk()会使$localKey无效

library/think/Validate.php
在 `think\Validate.php` 中存在调用方式的错误。
=> 修复Lang未使用facade方式调用

library/think/Validate.php
[https://github.com/top-think/framework/issues/1052](https://github.com/top-think/framework/issues/1052)
对于移除规则原本设计是 `true` 移除所有规则，但这会使的在 `Validate->checkItem` 中的 
`elseif (isset($this->remove[$field]) && in_array($info, $this->remove[$field])) {`
发生异常。
=> 修复自定义场景验证remove规则异常

library/think/File.php
`think\File` 里有一个`buildSaveName()`方法，如果没出现扩展名，没必要生成一个扩展名。尊重开发者的意志。
相关issue:[https://github.com/top-think/think/issues/834](https://github.com/top-think/think/issues/834)
=> 添加buildSaveName中自动补全扩展名的选项

library/think/Config.php, library/think/Route.php, library/think/console/command/optimize/Schema.php, library/think/db/Connection.php, library/think/db/Query.php, library/think/model/concern/SoftDelete.php, library/think/response/Download.php
我确定这是个隐患。注意到，字符串位置是从0开始，而不是从1开始的。如果没找到 `needle`，将返回 FALSE。
来自官网的提醒：
> Warning 此函数可能返回布尔值 FALSE，但也可能返回等同于 FALSE 的非布尔值。请阅读 布尔类型章节以获取更多信息。应使用 === 运算符来测试此函数的返回值。
详见:[http://php.net/manual/zh/function.strpos.php](http://php.net/manual/zh/function.strpos.php)
比如下载文件`think\response\Download` 中函数 `name` 有个补全扩展名的：
```
if ($extension && !strpos($filename, '.')) {
$this->name .= '.' . pathinfo($this->data, PATHINFO_EXTENSION);
}
```
如果下载的文件形如是 `.gitignore` 点开头的文件，则会变成 `..gitignore` 。
本 PR 将 `!strpos` 替换成 `false === strpos` ，已考虑兼容，不会出现影响兼容性的更新。
=> 改进strpos对子串是否存在的判断

library/think/Template.php
相关issue：[https://github.com/top-think/think/issues/868](https://github.com/top-think/think/issues/868)
模板文件里面出现如 `{extend .*name='xxx'.*}` 就被解析为模板继承自 `xxx` ，问题挺严重的。
=> [重要]修复解析extend标签的正则

library/think/route/RuleGroup.php
相关issue: #1499 
定义路由时自动补充默认模块或控制器，使得 `Route::get('test', 'index/test');` 与 `Route::get('test', 'index/index/test');` 行为一致。
=> 定义路由时自动补充默认模块或控制器

library/think/db/Query.php
#1512 
复现方式：
```
Db::view('user', 'id,name')->where('id','<',10)->orderRaw('RAND()')->select();
```
这是因为`orderRaw`会创建Expression对象，然后在 `db\Query.php` 的 parseView 函数中没处理好。使用 `->order(new Expression(...))` 也会引发这个异常。
=> 修复orderRaw异常

library/think/Validate.php
#1491 的补充
当 `null` 移除所有规则时，判断并不生效。
=> 修复自定义验证remove所有规则的异常

src/think/Cache.php
为 store 方法增加 $force 参数，并用于 $this->connect 调用
=> FIX：当使用complex缓存的时候，通过store方法选择驱动，提供给connect的参数类型错误

library/think/route/Rule.php
原来代码：
```php
1: foreach ($matches as $key => $val) {
2:                 if (false !== strpos($route, '<' . $key . '>')) {
3:                     $route = str_replace('<' . $key . '>', $val, $route);
4:                 } elseif (false !== strpos($route, ':' . $key)) {
5:                    $route = str_replace(':' . $key, $val, $route);
6:                }
7: }
```
设matches数组大小为n
str_replace替换某个字符串的时间复杂度为P
变量字符平均长度为k
route平均长度为m
第一行循环n次
如果第2行满足条件，则需要平均执行: `((m-k-2)/2)+P`
如果第4行满足条件，则第2行一定不满足条件，则需要平均执行：`(m-k-2)+[(m-k-1)/2]+P`
一共执行次数：`O1 = n*{[(m-k-2)/2]+P+(m-k-2)+[(m-k-1)/2]+P}`
strpos的源码：
https://github.com/php/php-src/blob/54dc07f3dc9fa2fcfeb2d2c6aebf79bd34ab041c/Zend/zend_operators.h#L170
str_replace的源码：
https://github.com/php/php-src/blob/67e0138c0dfd966624223911a0821f6c294ad1c6/ext/stand …
=> 路由变量替换的地方改进性能

library/think/route/Rule.php
当pathinfo分隔符不是默认的/;
并且路由路由表达式中含有相同的路径;
并且路由表达式中中含有动态变量;
例如：
pathinfo分隔符：-
路由：Route::get('test/test/:abc', 'index/index');
访问：http://127.0.0.1:8000/test-test-test
会报404模块不存在:test
原因：/library/think/route/Rule.php#1004行在使用str_replace进行替换时会多次替换导致正则表达式错误。
解决：对查找和替换的数组进行去重
=> 修复某些情况下生成路由的正则规则错误的BUG

library/think/File.php
=> 修复自定义上传验证，检测文件大小

src/think/db/Connection.php, src/think/db/Query.php
```php
use \think\db\Query;
AdminGroup::where('id', 'in', function($query){
$query->table('admin_user_group')->where('admin_user_id', 1)->field('admin_group_id');
})->field(['id', 'name'])->select();
```
以上代码会调用`Query::table()`方法设置`\think\db\Query->options['table']`
从代码逻辑来看`$options['table']`为string/array
异常问题:
当程序调用`\think\db\Query->getTable()`时因为返回类型是string,有可能会出现类型不匹配的错误
https://github.com/top-think/framework/blob/47713eaecb2ccdf01f22c7594f7fa152a65ef062/src/think/db/Query.php#L255-L264
类似问题的地方还有几处:
https://github.com/top-think/framework/blob/47713eaecb2ccdf01f22c7594f7fa152a65ef062/src/think/db/Connection.php#L504-L507
https://github.com/top-think/framework/blob/47713eaecb2ccdf01f22c7594f7fa152a65ef062/src/think/db/Connection.php#L516-L525 …
=> 5.2  Query:table('table') 报数据类型不匹配的错误

src/think/middleware/AllowCrossDomain.php
添加Access-Control-Allow-Credentials并设置为true
新版浏览器对 Access-Control-Allow-Origin 设置为 * 通配符也进行报错
修改根据cookie域名 实现动态多域名跨域
=> 修复google浏览器跨域报错问题

library/think/Validate.php
当validate的rule出现类似['require', 'in'=>[1,2,3]]这种规则，array_unique默认是SORT_STRING规则进行去重，而数组无法转换为字符串，出现报错，SORT_REGULAR则保留原有类型进行去重
=> 修复validate规则里面出现二维数组时的错误

library/think/db/Query.php
Query的getPk方法只是判断$options是否是array，然后取$options['table']的值，此处应增加判断$options是否存在’table‘的key再取$options['table']的值
=> 修复Query getPk 方法判断table字段是否存在问题

composer.json, src/think/console/Table.php
修复前：
```
+----+-----------------+----------------+----------------+--------+
| id | genre           | name           | nick           | status |
+----+-----------------+----------------+----------------+--------+
| 2  | 超级管理员 | admin          | admin          | 正常 |
| 3  | 超级管理员 | admin123       | admin123       | 正常 |
| 4  | 超级管理员 | 123456         | 123456         | 正常 |
| 5  | 超级管理员 | ttttttt        | ttttttt2311    | 正常 |
| 7  | 超级管理员 | admin_6R3jDCTu | admin_6R3jDCTu | 正常 |
| 8  | 超级管理员 | admin_nkLrxsQF | admin_nkLrxsQF | 正常 |
+-----------------------------------------------------------------+
| test                                                            |
+-----------------------------------------------------------------+
| 1  | 1               | 1              | 1              | …
```
=> 修复控制台表格渲染对多字节字符的兼容性

library/think/Collection.php
开发时发现以下语句返回的结果并非预期：
```
$collection = new \think\Collection($array);
$collection->where('id', 'IN', [1, 2]);
```
实际返回结果应该含有2个，但实际为空
=> 优化 Collection::where 操作符大小写

src/think/Session.php
由于 php-redis 5 后续版本弃用了 Redis::delete()，修正 session 驱动调用 php-redis 的 delete 方法为 del 方法。
> 引用自 https://github.com/phpredis/phpredis#del-delete-unlink
> Note: delete is an alias for del and will be removed in future versions of phpredis.
> https://github.com/phpredis/phpredis/pull/1572
> https://pecl.php.net/package-changelog.php?package=redis&release=5.0.0
=> fix(session): 移除 session 驱动中 php-redis 的 del 方法别名

src/helper.php
默认情况下，validate助手函数在验证失败后将默认抛出异常。增加了 $failException 参数以支持设置验证失败后是否抛出异常。
=> feat(helper): 改进validate助手函数,支持设置是否抛出异常

src/helper.php, src/think/exception/HttpException.php
修复调用 `abort(401)` 时报错 `Wrong parameters for think\exception\HttpException([string $message [, long $code [, Throwable $previous = NULL]]])`
=> [6.0] 修复严格类型下 HttpException->$message 不能为 null

src/think/cache/driver/File.php, src/think/session/driver/File.php
为避免溢出问题，应使用减法来代替。可参照项目中的其他地方的处理方式：
https://github.com/top-think/framework/blob/abaec0344bbd57671e29010d2d7a2c1d609861a4/src/think/session/driver/File.php#L150
=> 避免时间戳相加整型溢出

src/think/middleware/CheckRequestCache.php
1. 回调函数增加传递 `$request` 参数；
2. 回调函数率先运行，即以回调函数的反正值作为 `request_cache_key` 的值，然后走后续判断和替换逻辑。
=> 增强中间件CheckRequestCache的实用性

src/think/route/Url.php
配置了 `'url_common_param'=>false` 时，对于：
```
url('test', ['name'=>'tom', 'desc'=>''])    生成：'/index.php/Index/test/name/tom.html'        // 正确
url('test', ['name'=>'tom', 'desc'=>null])  生成：'/index.php/Index/test/name/tom/desc/.html'  // 有误
url('test', ['name'=>'tom', 'desc'=>false]) 生成：'/index.php/Index/test/name/tom/desc/.html'  // 有误
```
=> 防止路由标识生成URL时生成空字符串

src/think/middleware/CheckRequestCache.php
`cache` 的 `has` 方法会通过 `get` 形式获取，所以这边会访问两次临界区。如果驱动是文件缓存，就会读取两次文件。低概率情况下会发生，两次读取完成的时间差内，缓存正好过期，造成异常。
PR优化为只访问一次临界区。
=> 让中间件CheckRequestCache只访问一次临界区

src/think/session/Store.php
来自 https://www.php.net/manual/zh/function.uniqid.php 中的描述：
>Warning 此函数不保证返回值的唯一性。 由于绝大多数系统使用 NTP 或者类似服务调整系统的时间，所以系统时间经常发生变化。 此外，进程/线程可能不会返回唯一的 ID。 用 more_entropy 来增加唯一性的概率。
因此加入 `more_entropy` 参数，使得唯一ID更具唯一性。
=> 增强高并发下session_id生成的唯一性

src/think/Request.php
=> 修正 Request::remotePort 返回类型

src/think/middleware/AllowCrossDomain.php
1. 中间件中处理了 `OPTIONS` 请求，所以它也是被允许的；
2. 添加csrf头部允许，`Request` 类里验证令牌取的是 `X-CSRF-TOKEN` ，所以这里设置这个值。
=> 完善跨域中间件的响应头部

src/think/route/Url.php
=> 修正生成URL不传参数时，方法名为空#2063

src/think/middleware/CheckRequestCache.php
相关issue：#2040
比如设置请求缓存有效期半小时，一会后，设置为 1 分钟。那么数据应该过期，而当前会继续使用旧数据返回。
PR中将保存时的时间戳也保存下来，并进行二次校验。
=> 修复中间件CheckRequestCache使用过期数据

src/think/cache/driver/Memcache.php
`$key = getCacheKey($name)` 已为键添加了前缀，`has($key)` 会重新加一次，导致命中误判。可参考其他缓存驱动类中的inc方法。
=> 修复memcache驱动inc函数重复添加前缀问题

src/think/middleware/FormTokenCheck.php
=> 修复中间件FormTokenCheck无法启用问题

src/think/Request.php
php7.1+开始 array_walk_recursive 就不消耗指针了。见：https://bugs.php.net/bug.php?id=62607
所以PR仅是代码清理。
=> php7.1开始 array_walk_recursive 就不消耗指针了

src/think/Response.php
文档里的文件下载示例:
```
$file=  new \think\response\File('image.jpg');
return $file->name('my.jpg');
```
Response类会在send中进行 `$this->cookie->save();` 操作。而 File 类中cookie属性未设置而造成异常。
其他 Response 的子类都有在构造函数里对cookie进行设置。File 类理论上也可以这么做。相应的文档里的示例也需要更新。
PR选择比较保守的修复方式。
=> 修复FileResponse的cookie空对象异常

src/think/cache/driver/Memcached.php
官方 [Memcached.delete](https://www.php.net/manual/zh/memcached.delete.php) 支持 timeout 参数
**实现方法** 同 : [Memcache.delete](https://github.com/yinggaozhen/framework/blob/e35f3460c3b0f81d460d887add076a0ff29f2af1/src/think/cache/driver/Memcache.php#L173)
=> memcached delete 支持 timeout

src/tpl/think_exception.tpl
关闭调试模式时，仅有`$code`和`$message`变量，没有`$traces`变量
=> 修正异常页面的模板文件

src/think/Validate.php
Validate.php文件1084行 image_type_to_extension($type, false)方法，当$type为2时，返回jpeg,
而前面代码又把jpeg改为jpg,造成jpg!=jpeg,使得验证结果返回false
应该反了
=> 修改一个BUG，当使用验证类验证jpg结尾的图片报错问题

src/think/route/Dispatch.php
修复 #2123 的问题。
数据验证的``$this->autoValidate()``方法中会调用到``$this->request->param()``。
```php
/** @var Validate $v */
$v->message($message)
->batch($batch)
->failException(true)
->check($this->request->param());
```
其中有对请求参数和URL地址中的参数合并的操作：
```php
$this->param = array_merge($this->param, $this->get(false), $vars, $this->route(false));
```
但此时还没有路由参数还没有设置。
因此需要先执行``$this->request->setRoute()``方法设置路由参数后，再进行验证操作。
=> 修复使用路由验证后路由变量丢失的问题

library/think/cache/driver/Redis.php, library/think/process/pipes/Windows.php
php7.2+、Windows下会出现以下错误
```
count(): Parameter must be an array or an object that implements Countable
```
关联issue [#61](https://github.com/top-think/think-queue/issues/61)
5.1已[修复](https://github.com/top-think/framework/commit/c9b5134ac8bf2123fc9dc932e1d7b20c5d333d5d#diff-e94505412d60b41b93e10669cc45d186)
=> 5.0 Windows::write() 变量判断错误

library/think/db/builder/Mysql.php
->>获取数据不带有双引号，避免了双引号所引起的查询不匹配问题
=> 增加mysql json类型字段->>方式获取支持

src/think/log/driver/File.php
Log config `time_format` support `u` for real microseconds rather than `000000`.
* Log config example:
```
'time_format'    => 'Y-m-d H:i:s.u',
```
* Logs:
```
[2020-03-22 16:09:54.606361][info] Hello ThinkPHP.
```
=> Log config `time_format` support `u` for real microseconds.

src/think/log/driver/File.php
日志时间格式添加`u`微秒支持以后时区有问题，明确设置当前时区可以修正。
=> 修正日志记录时区问题

src/think/console/output/Descriptor.php
修复自定义命令别名比系统别名长导致报错问题
当前tp6下 如果使用了命令行 名称比系统名称长时候 执行 php think list时候报错
=> '修复自定义命令别名比系统别名长导致报错问题'

src/think/route/Rule.php
添加新特性：
允许路由规则中使用类名以实现更复杂的调度逻辑
使用举例：
```php
<?php
// router.php
// 路由文件
Route::get('service', \app\HelloDispatch::class);
```
```php
<?php
// 自定义的Dispatch类
declare (strict_types = 1);
namespace app;
use think\route\Dispatch;
class HelloDispatch extends Dispatch
{
public function exec()
{
return 'Hello world';
}
}
```
此特性的使用场景：
需要将多个接口使用同一个接入点调用的情形（例如手动实现的RPC）。
附一张我们小组的奇葩接口规范：
对于以上需求，如果采用此特性来定制调度逻辑，会非常简单：
```php
<?php
// router.php
// 路由文件
Route::get('/api/v2/rpc', \app\ServiceDispatch::class);
```
```php
<?php
declare (strict_types = 1);
namespace app;
use think\App;
use think\route\dispatch\Controller as ControllerDispatch;
/**
* Service Dispatcher
*/
class ServiceDispatch extends ControllerDispatch
{
protected $actionKey = 'action';
protected $defaultController = 'Index';
protected …
```
=> 添加特性：允许路由规则中使用类名以实现更复杂的调度逻辑

src/think/middleware/AllowCrossDomain.php
增加预检缓存 有效期1800秒
30分钟内同一条url再次请求，不再发送预检，也就是说30分钟内再次请求不会出现 options预检请求
=> 增加预检缓存 有效期1800秒

library/think/model/concern/SoftDelete.php
每次使用destory进行软删除的时候，如果传入空数组，则会造成删除所有数据。
=> SoftDelete删除条件做空判断

src/think/log/driver/Socket.php
导出`log-socket`驱动超时设置选项，以适配外网调试时网络波动延迟导致无法收到日志的问题。
=> 导出`SocketLog` 的`curl`超时设置

src/think/response/File.php
解决某些情况下响应文件请求时执行`ob_end_clean `时发生`ob_end_clean() failed to delete buffer. no buffer to delete`错误
close #2365
=> 改进响应文件请求时的缓冲清除

src/think/Request.php
PHP 8 当前方法错误提示
filter_var(): Argument #3 ($options) must be of type array|int, null given
=> $request->ip() 方法兼容PHP8

src/think/Validate.php
目前使用数组提示“:attribute必须在 :rule 范围内”。若不支持数组也应该抛异常。
=> 修复验证器in方法,between方法,使用数组,功能异常，Fixed #2408

src/think/Request.php
如果绑定根域名后 有其他域名访问会爆错 stristr 返回false rtrim 不支持bool参数
=> 子域名匹配 rtrim 参数类型错误

src/think/console/command/RunServer.php
通过php think run启动内置服务器默认是绑定在0.0.0.0:8000端口上的 但是显示的文案信息却是错误的
=> FIX 内置服务器启动默认host显示问题

src/think/Response.php
作用：发送cookie前先检查响应头header是否已发送
原因：在tp6.0框架中，调用easywechat或symfony等，并在这些包中已经响应了内容给浏览器，如果在tp打开了Session初始化中间件，会导致tp框架主动向浏览器发送PHPSESSION_ID的cookie，并在日志中报header已发送的错误。
场景：
一个项目中，有一部分接口需要用到session，所以需要打开tp6的session初始化。
而另外一些接口不需要用session（如微信开发的被动消息服务端，直接在easywechat包内响应内容），但由于项目的其他接口要用到session，所以项目是打开session初始化中间件的，当调用不需要用session的接口时，就会一直报header已发送的错误。
=> 发送cookie前先检查header是否已发送

src/think/Container.php
getObjectParam 获取参数值时，优先使用声明的默认值，而不是实例化一个对象，因为某些类型约束声明可能是abstract
如：Pivot模型
=> fix: Container getObjectParam

src/think/route/dispatch/Controller.php, tests/EnvTest.php, tests/RouteTest.php
> 当前控制器中间件的参数是写在键名里，所以不能支持动态参数，比如传一个对象，如此改进后就可以了
用法如下，定义middleware方法，这个可以自己定义,放在BaseController中，最终写入`middleware`属性里元素的格式是`['middleware'=>['SomeMiddleware', [...params]],'options'=>[]]`即可
```php
<?php
namespace app\controller;
use app\middleware\Auth;
class Index 
{
protected $middleware = [];
protected $user;
public function __construct()
{
$this->middleware('SomeMiddleware', $this->user)->only('hello');
}
protected function middleware($middleware, ...$params)
{
$options = [];
$this->middleware[] = [
'middleware' => [$middleware, $params],
'options'    => &$options,
];
return new class($options) {
protected $options;
public function __construct(array &$options)
{
$this->options = &$options;
}
public function only($methods)
{
$this->options['only'] = is_array($methods) ? $methods : …
```
=> 控制器中间件支持动态参数

library/think/Request.php
当过滤值为null时,不去执行过滤函数;
兼容php8.1`Passing null to parameter #1 ($string) of type string is deprecated`问题
=> tp6的优化过滤函数,兼容php8.1;

src/tpl/think_exception.tpl
参考 cdn 官网公告：https://www.bootcdn.cn/
=> [6.0] 更新 prettify.js 为新的 cdn 地址

src/think/cache/Driver.php
在高并发频繁读取缓存的场景下 会出现has判断缓存存在的时候返回true 但是get读取缓存的时候缓存恰好失效(此时返回默认null)  所以需要加上一层判断 当读取缓存失效的时候 执行对应业务逻辑 而不是直接返回null
=> FIX:remember缓存读取问题修复

src/think/console/output/driver/Console.php
改动的代码只有一处调用
Console::getTerminalDimensions()
```
if (preg_match('/^(\d+)x(\d+)$/', $this->getMode(), $matches)) {
return [(int) $matches[1], (int) $matches[2]];
}
```
相关报错信息
```
PHP Fatal error:  Uncaught think\exception\ErrorException: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in D:\wamp64\www\wsdwl.i0w.cn\vendor\topthink\framework\src\think\console\output\driver\Console.php:175
```
=> 兼容 PHP 8.1

src/think/filesystem/driver/Local.php
=> Windows环境下文件访问地址不正确

src/think/Request.php
当不存在指定的header时，很明显返回值可能是null，但@return中没有写。在使用phpstan静态检查时发现该问题。
=> 改进Request类中header方法的返回值

src/think/Request.php
当请求类型为POST，传递类型为json时，以curl为例：
```shell
curl --location --request POST 'http://test.cn/' \
--header 'Content-Type: application/json' \
--header 'Content-Length: 14' \
--data-raw '{"name": null}'
```
我们在控制器中，使用如下代码时
```php
<?php
namespace app\controller;
use app\Request;
class Index {
public function index(Request $request){
var_dump($request->param());
var_dump($request->only(['name']));
}
}
```
返回的结果为
```
array(1) {
["name"]=> null
}
array(0) {
}
```
显然，在`POST`请求中`name`字段存在且为空值。但是only方法却过滤了这个值，原因是因为在`Request`这个类的第1493行，采用`isset`方法。
```php
if (!isset($data[$key])) {
continue;
}
```
问题原因参考如下代码：
```php
<?php
$data = ['name' => null];
var_dump(isset($data['name']));
var_dump(key_exists('name', $data));
```
输出为：
```
false
true
```
=> 修复传空值被忽略的情况

src/think/App.php
因Filesystem相关库已剥离，App基础类中的声明属性理应删除
=> 移除基础类中Filesystem申明属性

src/think/Container.php
```
app()->invoke(function ($index, ...$args) {
var_dump(func_get_args());
}, [1, 2, 3]);
输出：
array(2) {
[0]=>
int(1)
[1]=>
int(2)
}
```
修复容器绑定参数时，可变参数参数丢失问题。
=> fix: container绑定参数时可变参数处理

library/think/db/Query.php
如当定义`$globalScope = ['system_user_id']` 时：查询范围的回函数名应为：`scopeSystemUserId`。
- [查询范围文档](https://www.kancloud.cn/manual/thinkphp5_1/354053)
=> fix: 修正定义全局的查询范围时的回调名称

src/think/cache/driver/File.php
参照于session文件写入时加锁：
https://github.com/top-think/framework/blob/3c01a4e9bcb401d109a9c098b9fbc53e5e447024/src/think/session/driver/File.php#L170-L173
=> 文件缓存驱动写文件时加锁

src/think/initializer/Error.php
修复内容：在PHP发生错误中止时，内存中的日志没有写入到文件，中间件end回调没有执行。
复现如下：
```php
<?php
namespace app\index\controller;
use app\BaseController;
class Index extends BaseController
{
public function index()
{
app('log')->record('这个日志不会被写入');  // 这是一个发生错误前，写入到内存的日志
require_once './test.php';   // (test.php文件不存在时) 这是一个不可抛出的 shutdown 错误
return 'shutdown test';
}
}
```
解决思路：
路由分发到控制器后发生的所有Error和Exception都被中间件队列使用try catch捕获了Throwable，不会执行到set_exception_handler、set_error_handler这两个PHP函数, 所以正常走入口文件index.php的$response->send();$http->end($response); 
当PHP代码发生错误（不可抛出的错误）中止时，不能被Throwable捕获，但被register_shutdown_function捕获，进而由think\initializer\Error->appShutdown()处理，但是处理逻辑没有执行http的end回调。
=> fix: 修复发生错误中止时，日志没有写入、中间件end回调没有执行

src/think/Validate.php
场景：v6.0升级v6.1报错。request获取请求参数，老版本是使用isset过滤了null值的参数，新版本使用key_exists不过滤传的所有参数，是合理的。但是导致插入报错，预期验证器里不写require，应该是如果该参数存在，就走后面的验证规则，结果是直接不验证null和空字符串，和自定义验证规则参数验证逻辑不符合。
建议统一成只要参数存在，就执行后面的验证规则，本条pr的处理，已检测修改所有内置规则。增加了nullable规则，除了require，可以和其他规则同时使用，表示值可以允许为null或者空字符串，建议加到开发文档上
=> 修改Validate内置规则对空值的处理

src/think/route/RuleGroup.php
开启了route.php中的route_rule_merge配置以后，该代码无法通过，查看了修改历史，发现是framework/src/think/route/RuleGroup.php中的addRuleItem代码修改导致的
=> 修复开启route_rule_merge后报错的问题

library/think/db/Builder.php
fix implode(): Passing glue string after array is deprecated. Swap the parameters
=> fix implode(), swap the parameters

src/think/console/command/optimize/Schema.php
在单应用模式下（多应用模式未测试，从源码看同样存在），使用命令行指令`php think optimize:schema`进行模型字段缓存生成时，如果 app/model 目录下还存在子目录，会抛出异常。
（单应用模式），在app/model目录中存在任意子目录
--app
----model
------common
--------BaseModel.php
------User.php
------Article.php
问题所在的Schema.php类中大致流程如下
1. 获取所有app/model中的文件及目录
2. （问题所在）遍历文件和目录，将其名称作为类名传给 buildModelSchema() 进行解析
3. new \ReflectionClass() 实例化反射类
4. 判断反射类是否是抽象类、是否继承 think\Model
由于第2步没有排除子目录，所以将目录名作为类名交给 buildModelSchema() 进行解析，导致抛出类不存在的异常。
在第2步遍历文件及目录时，先用class_exists()检测类是否存在
=> fix: 生成模型字段缓存的命令行指令在模型目录存在子目录时异常

src/think/console/command/RunServer.php
Windows 系统，如果没把 php 加到 `PATH` 系统环境变量里时，执行 `think run` 会报 `'php' is not recognized as an internal or external command`。
```
D:\wamp64\bin\php\php8.1.18\php.exe think run -vvv
```
```
ThinkPHP Development server is started On <http://0.0.0.0:8000/>
You can exit with `CTRL-C`
Document root is: D:\wamp64\www\tp80.i0w.cn\public
'php' is not recognized as an internal or external command,
operable program or batch file.
```
=> Feat: Use PHP_BINARY instead of php

src/helper.php, src/think/Request.php, src/think/facade/Request.php
从代码`src\think\Request.php`来看：
```
protected function getFilter($filter, $default): array
{
if (is_null($filter)) {
$filter = [];
} else {
$filter = $filter ?: $this->filter;
if (is_string($filter) && !str_contains($filter, '/')) {
$filter = explode(',', $filter);
} else {
$filter = (array) $filter;
}
}
$filter[] = $default;
return $filter;
}
```
filter参数是支持null的，意味着不调用任何过滤函数。
并且filter应该支持null，虽然空数组也能达到效果，但null更具有实际意义。
但在8.0版本中，并不接受null，如果不进行声名则无法再php8.0中正确运行，本次提交为修复该错误。
```
think\\Request::input(): Argument #4 ($filter) must be of type array|string, null given, 
```
=> 为requre获取参数方法指定正确的filter类型
