tests/thinkphp/library/think/urlTest.php
=> 增加Url类单元测试

library/think/Response.php
fixed https://github.com/top-think/think/issues/438
=> hook return_data 逻辑错误

library/think/cache/driver/Redisd.php, library/think/session/driver/Redis.php, tests/thinkphp/library/think/cache/driver/redisdTest.php, tests/thinkphp/library/think/debugTest.php, tests/thinkphp/library/think/sessionTest.php
1，部分重构Redisd驱动，兼容最新的phpredis驱动特性
2，修复一些hhvm下无法通过CI的地方
=> 部分重构Redisd驱动，修复一些hhvm下无法通过CI的地方

library/think/Model.php
修改查询后直接save update_time 等autoTimeField时间字段不更新bug
=> 修改查询后直接save update_time 等autoTimeField时间字段不更新bug

library/think/Url.php
=> URL生成的一个bug，含参数时

library/think/Request.php
修正路由无法区分 hello 和  hello/，这应该是两个地址，一个是文件，一个是路径
=> 修正路由无法区分 hello 和  hello/

library/think/db/Query.php
原代码第 `1976` 行 `$this->getRealSql($sql,$this->bind);` 应该修改为 `$this->connection->getRealSql($sql,$this->bind);`
=> Query 的 delete() 方法使用 fetchSql() 报错

library/think/session/driver/Memcached.php
=> 增加了连接memcached时账号密码的属性

library/think/db/builder/Mysql.php
=> 修正MYSQL数据库UPDATE JOIN语句语法错误

helper.php
注：只支持applacation/common.php内重写，模块下的函数库不可以
=> 助手函数 是否定义判断，方便用户重写helper函数

library/think/cache/driver/Memcached.php
=> 为cache中的memcached增加连接时账号密码的属性

library/think/Route.php
=> 修正一处函数名拼写错误

.gitignore
忽略mac osx系统下自动产生的 .DS_Store 文件
=> ignore .DS_Store of osx

library/think/db/builder/Pgsql.php
=> json字段支持参数错误

library/think/Lang.php
对于多语言的项目,需要设置多语言标注cookie,而且需要控制该cookie的存储周期.在Lang类中增加设置cookie过期时间的方法.
=> 增加方法-多语言-设置多语言cookie过期时间

library/think/Controller.php
=> 在控制器中调用request和view增加类型提示

library/think/Template.php
=> 修正模板标签默认值某些情况无效bug

library/think/console/command/optimize/Autoload.php
之前的问题是，配置了`root_namespace`的类库，用`php think optimize:autoload`命令不会生成相应的类库映射缓存。
=> 支持自定义的根命名空间也可以生成类库映射缓存

library/think/console/output/driver/Console.php
=> 命令行输出驱动增加getFormatter方法

library/think/Session.php
=> 修复 重新生成session_id bug

library/think/cache/driver/File.php, library/think/cache/driver/Lite.php, library/think/cache/driver/Sqlite.php
```php
$connection = Cache::init();
$connection->dec('test'); // 目前test = 1,预期应该是-1
```
=> 调整部分CacheDriver::dec在为空的时候结果不符合预期的问题

library/traits/model/SoftDelete.php, tests/thinkphp/library/traits/model/.gitignore, tests/thinkphp/library/traits/model/softDeleteTest.php
1、新增SoftDelete类注释，有助于IDE更好进行识别
2、新增SoftDelete单元测试
=> 新增SoftDelete单元测试

base.php, library/think/App.php, library/think/Config.php, library/think/Error.php, library/think/Loader.php, library/traits/controller/Jump.php, library/traits/model/SoftDelete.php, library/traits/think/Instance.php, start.php
想通过该分支，逐步完成框架代码格式的美化，完善相应的注释信息，调整代码格式，尽量避免超长的代码行，以便于阅读查看。
美化中不设计代码执行逻辑的修改，仅有个别地方调整 if...else 的逻辑等，不影响代码块的功能和结果。
目前已完成基础部分的源码文件修改，后续会继续进行更多的文件调整。
=> 格式化 start、base、traits 和 App、Config、Error、Loader 代码的样式

library/think/Build.php, library/think/Cache.php, library/think/Collection.php, library/think/Config.php, library/think/Console.php, library/think/Controller.php, library/think/Cookie.php
调整部分代码的样式，并添加注释。
由于目前对测试部分不是很了解，所以出现的测试未覆盖问题暂时无法解决，以后了解测试之后再来完善相关的测试覆盖。
=> 调整 Build、Cache、Collection、Config、Console、Controller、Cookie 的代码样式

library/think/Db.php, library/think/Debug.php, library/think/Env.php, library/think/Error.php, library/think/Exception.php, library/think/File.php, library/think/Hook.php, library/think/Lang.php, library/think/Loader.php, library/think/Log.php
补全 Db、Debug、Env、Error、Exception、File、Hook、Lang、Loader、Log 类的文档，调整代码样式。
有部分代码的条件逻辑的结构做过调整，如`Loader::autoload()`方法中，L82 部分。检查过，并未改变原意。
=> 补全 Db、Debug、Env、Error、Exception、File、Hook、Lang、Loader、Log 类的文档，调整代码样式

library/think/Collection.php
１、uasort和shuffle参数都是引用，函数返回值会和预期不符
２、调整参数命名
=> 修复Collection bug

library/think/cache/driver/File.php
$_SERVER['REQUEST_TIME']改time()
=> 修正在长连接时过期无效的情况！

library/think/Request.php
=> 修正IPv6地址无法正确返回的问题

library/think/App.php
=> 解决注解路由配置不生效的问题

library/think/Build.php
276行  Route::resourece   单词"resourece"拼写错误， 正确的应该是 resource
=> 资源路由生成错误修复

library/think/Env.php
相关issue: [https://github.com/top-think/framework/issues/1428](https://github.com/top-think/framework/issues/1428)
=> Env::get中环境变量前缀可选项 #1428

library/think/console/output/question/Choice.php
相关issue:[https://github.com/top-think/framework/issues/1224](https://github.com/top-think/framework/issues/1224)
=> 修复choice无法用值选择第一个选项问题

library/think/Validate.php
Rt
```php
<?php
function getDataValue($data, $key) {
if (is_numeric($key)) {
$value = $key;
} elseif (strpos($key, '.')) {
// 支持多维数组验证
foreach (explode('.', $key) as $key) {
if (!isset($data[$key])) {
$value = null;
break;
}
$value = $data = $data[$key];
}
} else {
$value = isset($data[$key]) ? $data[$key] : null;
}
return $value;
}
$object = [
'a' => [
'b' => [
'c' => 'ok'
],
'x' => [
'y' => 'yes'
],
'z' => 'biu...'
]
];
$value1 = getDataValue($object, 'a.b.c');
$value2 = getDataValue($object, 'a.b.c.d');
$value3 = getDataValue($object, 'a.z');
print_r(compact('value1', 'value2', 'value3'));
```
=> 验证器支持多维数组取值验证

library/think/Template.php
PR[https://github.com/top-think/framework/pull/1506](https://github.com/top-think/framework/pull/1506) 的补充。改进block标签的解析。
=> 改善解析block标签的正则

library/think/Validate.php
=> 修复不会运行自定义验证函数的情况

library/think/Request.php
=> 修复array_walk_recursive后只重置数组外层指针问题

library/think/Request.php, library/think/db/Builder.php
=> 修复 array_walk_recursive 在低于PHP7.1消耗内部指针问题

library/think/Request.php
=> 改进Request类的has方法，支持patch

src/think/Validate.php
ctype_digit ( string $text ) : bool
=> 修正纯数字检测参数类型转换问题

src/think/middleware/AllowCrossDomain.php
1. handle 第三个参数添加Nullable类型标示
2. 当前跨域请求添加相关头部
=> 当前跨域请求添加相关头部

src/think/Request.php
=> 修改isPjax判断

src/think/route/Url.php
=> 修复某些情况下URL会多一个冒号

library/think/Url.php
=> [5.1]修复某些情况下URL会多一个冒号

src/think/cache/Driver.php, src/think/response/Redirect.php
Reverts top-think/framework#2059
=> Revert "优化缓存命中取值"

src/think/log/driver/Socket.php
- 统一使用 request 对象获取数据。
- 支持设置输出时自动展开日志级别。
- 改进 json 序列化，忽略无法序列化数据，尽可能把日志推送出去。
=> 改进 SocketLog 驱动

src/think/exception/Handle.php, src/tpl/think_exception.tpl
=> 支持输出完成异常链调试信息

src/think/exception/Handle.php, src/tpl/think_exception.tpl
Reverts top-think/framework#2073
=> Revert "支持输出完整的异常链信息"

src/think/exception/Handle.php, src/tpl/think_exception.tpl
- 解决 #2073 存在未定义变量的问题。
- 解决 #2073 响应 json 时最小输出不一致的问题。
- 堆栈信息支持折叠，以解决页面过长问题（输出时默认折叠除首个异常外的其它堆栈信息）。
=> 支持渲染完整的异常链信息

src/think/log/driver/Socket.php
- 支持自定义服务通信端口，以支持 [socket-log-server](https://github.com/NHZEX/socket-log-server) 和 docker部署重映射端口。
- 支持自定义渲染日志头部，提供自定义日志头部的能力。
```php
'remote' => [
// 日志记录方式
'type'           => 'socket',
// socket服务器地址
'host'           => env_get('LOG_REMOTE_HOST', '127.0.0.1'),
'port'           => env_get('LOG_REMOTE_PORT', 1116),
// 日志强制记录到配置的 client_id
'force_client_ids' => explode(',', env_get('LOG_REMOTE_FORCE_CLIENT', 'develop')),
// 限制允许读取日志的 client_id
'allow_client_ids' => explode(',', env_get('LOG_REMOTE_ALLOW_CLIENT', 'develop')),
// 日志处理
'processor'      => null,
// 日志输出格式化
'format'         => '[%s][%s] %s',
// 是否实时写入
'realtime_write' => false,
// 日志头渲染
'format_head'    => function($uir, \think\App $app) {
$runtime     = round(microtime(true) - $app->getBeginTime(), 10);
$time_str    = ' …
```
=> 扩展SocketLog驱动

library/think/cache/driver/Redis.php
=> 规范Redis::has()返回值

library/think/model/relation/HasOne.php
edit this class function name "has", add use param "$softDelete"
=> hasone model update has function

src/think/Validate.php
调整场景执行优先级，以允许在`scene*`场景调用中使用`rule`方法添加规则
=> [6.0] 调整 Validate 场景执行优先级

src/think/console/command/Clear.php
=> clear命令支持多层级目录

src/helper.php
=> 修复助手函数public_path路径

library/think/Model.php, library/think/db/Query.php, library/think/model/relation/MorphTo.php
优化Model注释，ide可指向正确的Model
Model增加paginate方法注释
还有代码不知道谁在Debug.php增加了个TODO，通过不了pr。。。
如下是phpstorm的提示：
在编码时很舒服，望添加。
=> 修复多态关联预加载field无效

src/think/console/command/Clear.php
=> 为清理指令添加仅删除过期文件的选项

src/think/facade/App.php, src/think/facade/Cache.php, src/think/facade/Config.php, src/think/facade/Console.php, src/think/facade/Cookie.php, src/think/facade/Env.php, src/think/facade/Event.php, src/think/facade/Filesystem.php, src/think/facade/Lang.php, src/think/facade/Log.php, src/think/facade/Middleware.php, src/think/facade/Request.php, src/think/facade/Route.php, src/think/facade/Session.php, src/think/facade/Validate.php, src/think/facade/View.php
facade类库增加@method注释，方便IDE对方法进行智能提示。
=> facade类库增加@method注释

src/think/route/Resource.php
=> 资源路由支持设置变量规则

library/think/Request.php
=> think/Request host方法获取域名改进

src/think/console/command/make/Middleware.php
=> 修复命令行创建中间件命名空间无效 bug

src/think/Request.php
1：typeCast 函数权限修改为protected，继承中可以继续复用
2：注释 fixed
=> Fix permission

src/think/console/command/Make.php
=> Fix make:controller error

composer.json, src/think/route/Dispatch.php, tests/DispatchTest.php
- fix: https://github.com/yansongda/pay/issues/451#issuecomment-877936908
=> feat: psr7 response

tpl/think_exception.tpl
参考 cdn 官网公告：https://www.bootcdn.cn/
=> [5.1] 更新 prettify.js 为新的 cdn 地址

src/think/Lang.php
=> Fix switchLangSet missing setLangSet

src/think/Route.php, src/think/facade/Route.php
=> 增加 HEAD 路由支持
